### ISSUE TITLE
Stability Analyzer tool window ignores plugin settings

### ISSUE THREAD

**Issue by rlnt** [skydoves/compose-stability-analyzer#74]
**Please complete the following information:**
- Library Version 0.6.0
 
**Describe the Bug:**

When entering ignored type patterns in the plugin settings, the IDE tool window still shows issues for these types. The inline hints and warnings within the editor are gone but the tool window still shows them as problematic.

**Expected Behavior:**

If I ignore a specific type, they should also be ignored in the analyzer IDE tool window.

**Comment by skydoves** [comment]
Hi @rlnt, a new version 0.6.1 has been released, and now it should be fixed. Thank you for your report!

**Comment by rlnt** [comment]
This doesn't seem to be fixed. I updated the IDEA plugin as well as the Gradle dependency to 0.6.1, started my app, clicked the refresh icon in the tool window, and it still shows unstable types I have in my ignore list.

As an example, I have `androidx.navigation.NavController` in my "Ignored Type Patterns", which works fine with the inlay hints and the gutter icon.
<img width="621" height="181" alt="Image" src="https://github.com/user-attachments/assets/75c4370b-fb91-4bbb-9d00-a6a56806e2f6" />

But it still shows in the tool window.
<img width="828" height="355" alt="Image" src="https://github.com/user-attachments/assets/baecb1ae-9b97-45b4-a7b5-c98092964bfb" />

**Comment by skydoves** [comment]
Hi @rlnt, a new version 0.6.2 has been released. Please check if it works well from your side. Thank you!

**Comment by rlnt** [comment]
Works now, thanks a lot!
